"""Faz 1 B1.1: karar, denetim, onay, feedback, policy, insight tablolari

Revision ID: 0384bcdc8515
Revises:
Create Date: 2026-07-30 14:44:49.306531

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0384bcdc8515"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "decision",
        sa.Column("karar_id", sa.Uuid(), nullable=False),
        sa.Column(
            "alan",
            sa.Enum("stok", "finans", "satis", "uretim", name="alan", native_enum=False),
            nullable=False,
        ),
        sa.Column(
            "tip",
            sa.Enum(
                "stok.siparis",
                "stok.tasfiye",
                "stok.tedarikci_degisim",
                "stok.aksiyon_yok",
                name="karartipi",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("aksiyon", sa.JSON(), nullable=False),
        sa.Column("tahmini_tutar_tl", sa.Float(), nullable=False),
        sa.Column("geri_alinabilir", sa.Boolean(), nullable=False),
        sa.Column("guven", sa.Float(), nullable=False),
        sa.Column("tetiklenen_kurallar", sa.JSON(), nullable=False),
        sa.Column("ozellikler", sa.JSON(), nullable=False),
        sa.Column("model_surumleri", sa.JSON(), nullable=False),
        sa.Column("uretim_zamani", sa.DateTime(), nullable=False),
        sa.Column(
            "politika_sonucu",
            sa.Enum(
                "oto_uygula",
                "onay_kuyrugu",
                "aksiyon_yok",
                name="politikasonucu",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("uygulandi", sa.Boolean(), nullable=False),
        sa.Column(
            "otonomi_seviyesi",
            sa.Enum(
                "shadow", "advisory", "threshold", "off", name="otonomiseviyesi", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column("risk_skoru", sa.Float(), nullable=False),
        sa.Column("gerekce_kodlari", sa.JSON(), nullable=False),
        sa.Column("gerekce_metni", sa.Text(), nullable=True),
        sa.Column(
            "guard_sonucu",
            sa.Enum(
                "gecti",
                "yeniden_uretildi",
                "sablona_dustu",
                "atlandi",
                name="guardsonucu",
                native_enum=False,
            ),
            nullable=True,
        ),
        sa.Column("llm_model_adi", sa.String(length=255), nullable=True),
        sa.Column("gerekce_uretim_ms", sa.Integer(), nullable=True),
        sa.Column("olusturma_zamani", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("karar_id"),
    )
    with op.batch_alter_table("decision", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_decision_alan"), ["alan"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_decision_olusturma_zamani"), ["olusturma_zamani"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_decision_politika_sonucu"), ["politika_sonucu"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_decision_risk_skoru"), ["risk_skoru"], unique=False)
        batch_op.create_index(batch_op.f("ix_decision_tip"), ["tip"], unique=False)
        batch_op.create_index(batch_op.f("ix_decision_uygulandi"), ["uygulandi"], unique=False)

    op.create_table(
        "policy",
        sa.Column(
            "karar_tipi",
            sa.Enum(
                "stok.siparis",
                "stok.tasfiye",
                "stok.tedarikci_degisim",
                "stok.aksiyon_yok",
                name="karartipi",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("esik_oto_uygula_tutar_tl", sa.Float(), nullable=False),
        sa.Column("esik_oto_uygula_min_guven", sa.Float(), nullable=False),
        sa.Column("daima_onay_gerektirir", sa.Boolean(), nullable=False),
        sa.Column("aktif", sa.Boolean(), nullable=False),
        sa.Column("aciklama", sa.Text(), nullable=True),
        sa.Column("guncelleme_zamani", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("policy", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_policy_aktif"), ["aktif"], unique=False)
        batch_op.create_index(batch_op.f("ix_policy_karar_tipi"), ["karar_tipi"], unique=True)

    op.create_table(
        "approval",
        sa.Column("karar_id", sa.Uuid(), nullable=False),
        sa.Column(
            "durum",
            sa.Enum(
                "bekliyor",
                "onaylandi",
                "reddedildi",
                "duzeltildi",
                name="onaydurumu",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("olusturma_zamani", sa.DateTime(), nullable=False),
        sa.Column("karar_zamani", sa.DateTime(), nullable=True),
        sa.Column("karar_veren", sa.String(length=255), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["karar_id"], ["decision.karar_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("approval", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_approval_durum"), ["durum"], unique=False)
        batch_op.create_index(batch_op.f("ix_approval_karar_id"), ["karar_id"], unique=True)
        batch_op.create_index(
            batch_op.f("ix_approval_olusturma_zamani"), ["olusturma_zamani"], unique=False
        )

    op.create_table(
        "decision_audit",
        sa.Column("karar_id", sa.Uuid(), nullable=False),
        sa.Column("girdi_hash", sa.String(length=64), nullable=False),
        sa.Column("tetiklenen_kurallar", sa.JSON(), nullable=False),
        sa.Column("model_surumleri", sa.JSON(), nullable=False),
        sa.Column("cikti", sa.JSON(), nullable=False),
        sa.Column(
            "guard_sonucu",
            sa.Enum(
                "gecti",
                "yeniden_uretildi",
                "sablona_dustu",
                "atlandi",
                name="guardsonucu",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("reddedilen_sayilar", sa.JSON(), nullable=False),
        sa.Column("zaman", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["karar_id"], ["decision.karar_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("decision_audit", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_decision_audit_girdi_hash"), ["girdi_hash"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_decision_audit_guard_sonucu"), ["guard_sonucu"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_decision_audit_karar_id"), ["karar_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_decision_audit_zaman"), ["zaman"], unique=False)

    op.create_table(
        "feedback",
        sa.Column("karar_id", sa.Uuid(), nullable=False),
        sa.Column(
            "tur",
            sa.Enum("onay", "red", "duzeltme", name="geribildirimturu", native_enum=False),
            nullable=False,
        ),
        sa.Column("duzeltilmis_aksiyon", sa.JSON(), nullable=True),
        sa.Column("yorum", sa.Text(), nullable=True),
        sa.Column("kullanici", sa.String(length=255), nullable=True),
        sa.Column("zaman", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["karar_id"], ["decision.karar_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("feedback", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_feedback_karar_id"), ["karar_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_feedback_tur"), ["tur"], unique=False)
        batch_op.create_index(batch_op.f("ix_feedback_zaman"), ["zaman"], unique=False)

    op.create_table(
        "insight",
        sa.Column("kosu_id", sa.Uuid(), nullable=False),
        sa.Column(
            "alan",
            sa.Enum("stok", "finans", "satis", "uretim", name="alan", native_enum=False),
            nullable=False,
        ),
        sa.Column("baslik", sa.String(length=255), nullable=False),
        sa.Column("metin", sa.Text(), nullable=False),
        sa.Column("onem_skoru", sa.Float(), nullable=False),
        sa.Column("karar_id", sa.Uuid(), nullable=True),
        sa.Column("zaman", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["karar_id"], ["decision.karar_id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("insight", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_insight_alan"), ["alan"], unique=False)
        batch_op.create_index(batch_op.f("ix_insight_karar_id"), ["karar_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_insight_kosu_id"), ["kosu_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_insight_onem_skoru"), ["onem_skoru"], unique=False)
        batch_op.create_index(batch_op.f("ix_insight_zaman"), ["zaman"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("insight", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_insight_zaman"))
        batch_op.drop_index(batch_op.f("ix_insight_onem_skoru"))
        batch_op.drop_index(batch_op.f("ix_insight_kosu_id"))
        batch_op.drop_index(batch_op.f("ix_insight_karar_id"))
        batch_op.drop_index(batch_op.f("ix_insight_alan"))

    op.drop_table("insight")
    with op.batch_alter_table("feedback", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_feedback_zaman"))
        batch_op.drop_index(batch_op.f("ix_feedback_tur"))
        batch_op.drop_index(batch_op.f("ix_feedback_karar_id"))

    op.drop_table("feedback")
    with op.batch_alter_table("decision_audit", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_decision_audit_zaman"))
        batch_op.drop_index(batch_op.f("ix_decision_audit_karar_id"))
        batch_op.drop_index(batch_op.f("ix_decision_audit_guard_sonucu"))
        batch_op.drop_index(batch_op.f("ix_decision_audit_girdi_hash"))

    op.drop_table("decision_audit")
    with op.batch_alter_table("approval", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_approval_olusturma_zamani"))
        batch_op.drop_index(batch_op.f("ix_approval_karar_id"))
        batch_op.drop_index(batch_op.f("ix_approval_durum"))

    op.drop_table("approval")
    with op.batch_alter_table("policy", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_policy_karar_tipi"))
        batch_op.drop_index(batch_op.f("ix_policy_aktif"))

    op.drop_table("policy")
    with op.batch_alter_table("decision", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_decision_uygulandi"))
        batch_op.drop_index(batch_op.f("ix_decision_tip"))
        batch_op.drop_index(batch_op.f("ix_decision_risk_skoru"))
        batch_op.drop_index(batch_op.f("ix_decision_politika_sonucu"))
        batch_op.drop_index(batch_op.f("ix_decision_olusturma_zamani"))
        batch_op.drop_index(batch_op.f("ix_decision_alan"))

    op.drop_table("decision")
    # ### end Alembic commands ###
